version: "3.8"

services:
  db:
    image: postgres:15
    container_name: auth_db
    restart: always
    environment:
      POSTGRES_USER: admin
      POSTGRES_PASSWORD: secret
      POSTGRES_DB: auth_db
    ports:
      - "5432:5432"
    volumes:
      - pgdata:/var/lib/postgresql/data

  backend:
    build: ./backend
    container_name: auth_backend
    restart: always
    depends_on:
      - db
    environment:
      DATABASE_URL: postgresql://admin:secret@db/auth_db
    ports:
      - "8000:8000"

#   frontend:  # Временно отключаем фронтенд
#     build: ./frontend
#     container_name: auth_frontend
#     restart: always
#     depends_on:
#       - backend
#     ports:
#       - "3000:3000"

volumes:
  pgdata:
